import Head from "next/head";
import { BsFillMoonStarsFill } from 'react-icons/bs'

export default function Home() {

  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl"><a href="https://github.com/teppley?tab=repositories" target="_blank">Created By: teppley</a></h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl hover:animate-spin" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-pink-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 hover:animate-pulse" href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
